resolver: lts-12.26
packages:
- .
- frontend-utils-samples
- servant-reflex
- jsaddle-warp
extra-deps:
- jsaddle-0.9.6.0
- jsaddle-dom-0.9.3.1
- ghcjs-dom-0.9.4.0
- reflex-0.6.1
- reflex-dom-0.5
- reflex-dom-core-0.5
- ref-tf-0.4.0.1
- zenc-0.1.1
- ghcjs-dom-jsaddle-0.9.4.0
- monoidal-containers-0.4.0.0
- pandoc-2.5
- HsYAML-0.1.1.3
- haddock-library-1.7.0
- hslua-1.0.2
- hslua-module-text-0.2.0
- string-interpolate-0.1.0.1
flags:
  reflex-dom:
    use-warp: true
build:
  haddock-hyperlink-source: false